### ISSUE TITLE
change the font to the same as in figma prototype

### ISSUE THREAD

**Issue by rohanrajpal** [SevaShop/sevashop#10]
Currently, the default chakra font is used. Change it to the one we use in the Figma prototype.

**Comment by rohanrajpal** [comment]
https://www.youtube.com/watch?v=G0cOQ79WKZE

**Comment by tomaroyal** [comment]
Best practices web fonts
1. Use a variable font
2. Preload your font file
3. Self-host instead of Google Fonts
4. use font-display: optional to prevent layout shift

Font used -> Poppins
[https://google-webfonts-helper.herokuapp.com/fonts/poppins?subsets=latin](https://google-webfonts-helper.herokuapp.com/fonts/poppins?subsets=latin)
